### ISSUE TITLE
Hosted documentation padding is uncomfortable on devices larger than mobile

### ISSUE THREAD

**Issue by caendesilva** [KickflipCli/kickflip-src#39] opened 2022-04-06 19:02 UTC
## Description
The padding on the main documentation article element is set to px-3 which in my opinion becomes increasingly uncomfortable as you scale up the page from mobile. 

## Steps to reproduce
1. Visit the hosted docs (https://kickflip.lucidinternets.com/)
2. Go to any page
3. Look at the article padding

## Expected behavior
The frontend could benefit from increasing the padding on the article element. Maybe md:px-6 and lg:px-8? This allows the content to breathe.

## Screenshots or output
Current:
![image](https://user-images.githubusercontent.com/95144705/162048044-a09bb43b-6e8c-4f2e-bef6-a38f3d904480.png)
Adding px-8
![image](https://user-images.githubusercontent.com/95144705/162048141-6fee7faf-7d7d-470c-8447-78fba07eef8d.png)

## Environment details
- OS: Windows 10
- Browser: Reproduced in Chrome 100, Chrome Canary, Firefox Dev Edition.

## Additional context
Happy to put in a PR! Is it https://github.com/KickflipCli/kickflip-docs/blob/main/resources/views/layouts/documentation.blade.php, or is there a source file somewhere else?

**Comment by caendesilva** [comment] 2022-04-06 19:35
The original padding `px-3` got lost somehow, I was using the new GitHub web editor which I am not yet super familiar with. But the merge commit looks as it is supposed to be and I tested the frontend locally and was happy with it. Hope it helped! :)

**Comment by mallardduck** [comment] 2022-04-06 19:41
Gonna keep this open for now as the fix hasn't "shipped" yet.

Seems that I need to fix the test snapshots to get unit tests passing.
I'll sort that out later. 😄

**Comment by caendesilva** [comment] 2022-04-06 20:38
Did it break with my PR? Because that feels weird lol

**Comment by mallardduck** [comment] 2022-04-06 20:41
Yes and no.

They've been broken for a little bit before this. However I do some unit
tests that render using the docs templates too. So this change would affect
those tests too.

Overall caused by breaking that is my doing though.

**Comment by mallardduck** [comment] 2022-04-11 20:36
All merged, repo-split and rebuilt via netlify now.
Looking good in prod thanks again @caendesilva

**Closed by mallardduck** 2022-04-11 20:36 UTC
Labels: bug

**Comment by caendesilva** [comment] 2022-04-12 16:22
Awesome!
